version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: graphql_db
      POSTGRES_PASSWORD: graphql_db


volumes:
  postgres_data: